import type {
  DispatchGatepass,
  Employee,
  Material,
  Notification,
  StoreInwardItem,
  UserRole,
  Visitor,
} from "./types";

export interface AppUser {
  id: string;
  name: string;
  username: string;
  password: string;
  role: UserRole;
  active: boolean;
  createdAt: string;
  department?: string;
  employeeId?: string;
  designation?: string;
}

export const defaultUsers: AppUser[] = [
  {
    id: "u1",
    name: "Admin User",
    username: "admin",
    password: "admin123",
    role: "admin",
    active: true,
    createdAt: "2026-01-01",
    employeeId: "EMP-ADM-001",
    designation: "System Administrator",
  },
  {
    id: "u2",
    name: "Dr. Rajesh Kumar",
    username: "employee",
    password: "emp123",
    role: "employee",
    active: true,
    createdAt: "2026-01-01",
    department: "R&D",
    employeeId: "EMP-RD-001",
    designation: "Senior Scientist",
  },
  {
    id: "u3",
    name: "Rajan Guard",
    username: "security",
    password: "sec123",
    role: "security",
    active: true,
    createdAt: "2026-01-01",
    employeeId: "EMP-SEC-001",
    designation: "Security Guard",
  },
  {
    id: "u4",
    name: "Suresh Kumar",
    username: "dispatch",
    password: "disp123",
    role: "dispatch_manager",
    active: true,
    createdAt: "2026-01-01",
    employeeId: "EMP-DM-001",
    designation: "Dispatch Manager",
  },
  {
    id: "u5",
    name: "Mohan Store",
    username: "store",
    password: "store123",
    role: "store_manager",
    active: true,
    createdAt: "2026-01-01",
    employeeId: "EMP-SM-001",
    designation: "Store Manager",
  },
];

export const employees: Employee[] = [
  { id: 1, name: "Dr. Rajesh Kumar", dept: "R&D" },
  { id: 2, name: "Priya Sharma", dept: "HR" },
  { id: 3, name: "Amit Singh", dept: "Production" },
  { id: 4, name: "Neha Gupta", dept: "Quality Control" },
  { id: 5, name: "Vikram Mehta", dept: "Admin" },
];

export const seedVisitors: Visitor[] = [
  {
    id: "VIS-20260406-0001",
    passId: "VIS-20260406-0001",
    name: "Rahul Verma",
    mobile: "+91 9876543210",
    address: "42, Rajpur Road, Dehradun, Uttarakhand",
    idProofType: "Aadhaar",
    idProofNumber: "XXXX-XXXX-1234",
    photo: "",
    numberOfVisitors: 1,
    additionalVisitors: [],
    personToMeetId: 1,
    personToMeetName: "Dr. Rajesh Kumar",
    department: "R&D",
    purpose: "Business Meeting",
    status: "Approved",
    inTime: "09:15 AM",
    date: "2026-04-06",
  },
  {
    id: "VIS-20260406-0002",
    passId: "VIS-20260406-0002",
    name: "Sunita Devi",
    mobile: "+91 8765432109",
    address: "15, Vasant Vihar, Dehradun",
    idProofType: "PAN",
    idProofNumber: "ABCDE1234F",
    photo: "",
    numberOfVisitors: 2,
    additionalVisitors: ["Ramesh Devi"],
    personToMeetId: 2,
    personToMeetName: "Priya Sharma",
    department: "HR",
    purpose: "Interview",
    status: "Pending",
    inTime: "10:30 AM",
    date: "2026-04-06",
  },
  {
    id: "VIS-20260406-0003",
    passId: "VIS-20260406-0003",
    name: "Manoj Tiwari",
    mobile: "+91 7654321098",
    address: "78, Saharanpur Road, Dehradun",
    idProofType: "Driving License",
    idProofNumber: "UK0720XX12345",
    photo: "",
    numberOfVisitors: 1,
    additionalVisitors: [],
    personToMeetId: 3,
    personToMeetName: "Amit Singh",
    department: "Production",
    purpose: "Material Delivery",
    status: "Exited",
    inTime: "08:45 AM",
    outTime: "11:20 AM",
    duration: "02:35:00",
    date: "2026-04-06",
  },
  {
    id: "VIS-20260406-0004",
    passId: "VIS-20260406-0004",
    name: "Kavita Rao",
    mobile: "+91 6543210987",
    address: "22, GMS Road, Dehradun",
    idProofType: "Passport",
    idProofNumber: "Z1234567",
    photo: "",
    numberOfVisitors: 3,
    additionalVisitors: ["Ravi Rao", "Anita Rao"],
    personToMeetId: 4,
    personToMeetName: "Neha Gupta",
    department: "Quality Control",
    purpose: "Audit Visit",
    status: "MeetingCompleted",
    inTime: "11:00 AM",
    meetingEndTime: "01:30 PM",
    date: "2026-04-06",
  },
  {
    id: "VIS-20260406-0005",
    passId: "VIS-20260406-0005",
    name: "Deepak Sharma",
    mobile: "+91 9988776655",
    address: "56, Saket Colony, Haridwar",
    idProofType: "Aadhaar",
    idProofNumber: "XXXX-XXXX-5678",
    photo: "",
    numberOfVisitors: 1,
    additionalVisitors: [],
    personToMeetId: 5,
    personToMeetName: "Vikram Mehta",
    department: "Admin",
    purpose: "Vendor Meeting",
    status: "Rejected",
    rejectionReason: "Prior appointment not confirmed",
    inTime: "02:00 PM",
    date: "2026-04-06",
  },
];

export const seedMaterials: Material[] = [
  {
    id: "MAT-20260406-0001",
    passId: "MAT-20260406-0001",
    name: "Chemical Reagents",
    quantity: "50",
    unit: "kg",
    company: "Merck India Pvt. Ltd.",
    vehicle: "UK07-CA-1234",
    driverName: "Suresh Pal",
    purpose: "Lab Supplies",
    type: "In",
    status: "Cleared",
    date: "2026-04-06",
    inTime: "08:30 AM",
    barcodeNumber: "MBAR2026040600001",
    destination: "Store",
  },
  {
    id: "MAT-20260406-0002",
    passId: "MAT-20260406-0002",
    name: "Packaging Material",
    quantity: "200",
    unit: "boxes",
    company: "PackPro Ltd.",
    vehicle: "DL09-AB-5678",
    driverName: "Ramesh Kumar",
    purpose: "Export Packaging",
    type: "Out",
    status: "Pending",
    date: "2026-04-06",
    inTime: "10:00 AM",
    barcodeNumber: "MBAR2026040600002",
  },
  {
    id: "MAT-20260406-0003",
    passId: "MAT-20260406-0003",
    name: "API Raw Material",
    quantity: "100",
    unit: "kg",
    company: "Sun Pharmaceuticals",
    vehicle: "HR26-CD-9012",
    driverName: "Vijay Singh",
    purpose: "Production Use",
    type: "In",
    status: "Cleared",
    date: "2026-04-06",
    inTime: "09:15 AM",
    barcodeNumber: "MBAR2026040600003",
    destination: "Store",
  },
  {
    id: "MAT-20260406-0004",
    passId: "MAT-20260406-0004",
    name: "Glass Vials",
    quantity: "500",
    unit: "pcs",
    company: "Borosil Ltd.",
    vehicle: "UK07-XY-7777",
    driverName: "Mohan Das",
    purpose: "Lab Equipment",
    type: "In",
    status: "Pending",
    date: "2026-04-06",
    inTime: "11:00 AM",
    barcodeNumber: "MBAR2026040600004",
  },
];

export const seedDispatchGatepasses: DispatchGatepass[] = [
  {
    id: "DGP-20260406-0001",
    passId: "DGP-20260406-0001",
    createdBy: "Suresh Kumar",
    vehicleNo: "UK07-CA-5555",
    driverName: "Kamal Singh",
    destination: "Delhi Warehouse",
    purpose: "Export Shipment",
    items: [
      {
        id: "item1",
        itemName: "Paracetamol API",
        quantity: "50",
        unit: "kg",
        batchNo: "B2026-001",
        description: "Export grade",
        verified: false,
      },
      {
        id: "item2",
        itemName: "Packaging Boxes",
        quantity: "200",
        unit: "pcs",
        batchNo: "PK-2026",
        description: "Standard packaging",
        verified: false,
      },
    ],
    status: "Submitted",
    date: "2026-04-06",
    createdTime: "09:00 AM",
    barcodeNumber: "DGP2026040600001",
  },
  {
    id: "DGP-20260406-0002",
    passId: "DGP-20260406-0002",
    createdBy: "Suresh Kumar",
    vehicleNo: "UP32-XY-1111",
    driverName: "Rakesh Verma",
    destination: "Mumbai Distribution Center",
    purpose: "Monthly Supply Dispatch",
    items: [
      {
        id: "item3",
        itemName: "Tablet Formulation",
        quantity: "5000",
        unit: "strips",
        batchNo: "TF-2026-012",
        description: "Blister packed",
        verified: false,
      },
    ],
    status: "Draft",
    date: "2026-04-06",
    createdTime: "10:30 AM",
    barcodeNumber: "DGP2026040600002",
  },
];

export const seedStoreInward: StoreInwardItem[] = [
  {
    id: "SI-001",
    materialId: "MAT-20260406-0001",
    materialName: "Chemical Reagents",
    quantity: "50",
    unit: "kg",
    company: "Merck India Pvt. Ltd.",
    receivedDate: "2026-04-06",
    receivedTime: "08:30 AM",
    acknowledged: false,
    gatepassId: "MIG-20260406-0001",
  },
  {
    id: "SI-002",
    materialId: "MAT-20260406-0003",
    materialName: "API Raw Material",
    quantity: "100",
    unit: "kg",
    company: "Sun Pharmaceuticals",
    receivedDate: "2026-04-06",
    receivedTime: "09:15 AM",
    acknowledged: false,
    gatepassId: "MIG-20260406-0002",
  },
  {
    id: "SI-003",
    materialId: "MAT-20260406-0004",
    materialName: "Glass Vials",
    quantity: "2000",
    unit: "pcs",
    company: "Borosil Ltd.",
    receivedDate: "2026-04-05",
    receivedTime: "02:00 PM",
    acknowledged: true,
    acknowledgedBy: "Mohan Store",
    notes: "All units inspected and stored in Rack B-12",
  },
];

export const seedNotifications: Notification[] = [
  {
    id: "notif-001",
    type: "visitor",
    title: "New Visitor Arrived",
    message: "Rahul Verma arrived to meet Dr. Rajesh Kumar",
    time: "09:15 AM",
    read: false,
  },
  {
    id: "notif-002",
    type: "approved",
    title: "Visitor Approved",
    message: "Rahul Verma's visit has been approved",
    time: "09:22 AM",
    read: false,
  },
  {
    id: "notif-003",
    type: "meeting",
    title: "Meeting Completed",
    message: "Kavita Rao's meeting with Neha Gupta is completed",
    time: "01:30 PM",
    read: true,
  },
  {
    id: "notif-004",
    type: "exit",
    title: "Exit Requested",
    message: "Manoj Tiwari has been cleared for exit",
    time: "11:20 AM",
    read: true,
  },
  {
    id: "notif-005",
    type: "material",
    title: "Material Entry",
    message: "Chemical Reagents (50 kg) received from Merck India",
    time: "08:30 AM",
    read: true,
  },
];

export const weeklyVisitorData = [
  { day: "Mon", visitors: 12, materials: 5 },
  { day: "Tue", visitors: 18, materials: 8 },
  { day: "Wed", visitors: 15, materials: 6 },
  { day: "Thu", visitors: 22, materials: 10 },
  { day: "Fri", visitors: 19, materials: 7 },
  { day: "Sat", visitors: 8, materials: 3 },
  { day: "Today", visitors: 5, materials: 3 },
];

export const entryTypeData = [
  { name: "Visitors", value: 68, color: "#D32F2F" },
  { name: "Materials", value: 22, color: "#2E7D32" },
  { name: "Others", value: 10, color: "#F57C00" },
];
